
- hosts: linux
  become: yes
  tasks:
    - name: "Ensure group - jinesh"
      group:
       name: jinesh
       state: present
 
    - name: "Add the user - jinesh"
      user:
       name: jinesh
       comment: jinesh
       group: jinesh
       update_password: on_create
