---
- hosts: linux
  become: yes
  tasks:
    - name: "Ensure group - rachit"
      group:
       name: rachit
       state: present
 
    - name: "Add the user - rachit"
      user:
       name: rachit
       comment: rachit
       group: rachit
       update_password: on_create
