---
- hosts: linux
  become: yes
  tasks:
    - name: "Ensure group - jai"
      group:
       name: revathi
       state: present
 
    - name: "Add the user - jai"
      user:
       name: revathi
       comment: revathi
       group: revathi
       update_password: on_create
